### ISSUE TITLE
Error running with latest ebpf agent

### ISSUE THREAD

**Issue by KalmanMeth** [netobserv/netobserv-ebpf-agent#143]
Using a previous image: quay.io/netobserv/netobserv-ebpf-agent:2d63d90 works OK for me.

Using the current main image: quay.io/netobserv/netobserv-ebpf-agent:main I get the following errors:

```
time="2023-06-28T08:53:46Z" level=info msg="starting NetObserv eBPF Agent"
time="2023-06-28T08:53:46Z" level=debug msg="configuration loaded" configuration="agent.Config{AgentIP:\"\", AgentIPIface:\"external\", AgentIPType:\"any\", Export:\"grpc\", TargetHost:\"flowlogs-pipeline\", TargetPort:2055, GRPCMessageMaxFlows:10000, Interfaces:[]string(nil), ExcludeInterfaces:[]string{\"lo\"}, BuffersLength:50, ExporterBufferLength:0, CacheMaxFlows:5000, CacheActiveTimeout:5000000000, Deduper:\"none\", DeduperFCExpiry:10000000000, DeduperJustMark:false, Direction:\"both\", LogLevel:\"debug\", Sampling:0, ListenInterfaces:\"watch\", ListenPollPeriod:10000000000, KafkaBrokers:[]string(nil), KafkaTopic:\"network-flows\", KafkaBatchMessages:1000, KafkaBatchSize:1048576, KafkaAsync:true, KafkaCompression:\"none\", KafkaEnableTLS:false, KafkaTLSInsecureSkipVerify:false, KafkaTLSCACertPath:\"\", KafkaTLSUserCertPath:\"\", KafkaTLSUserKeyPath:\"\", KafkaEnableSASL:false, KafkaSASLType:\"plain\", KafkaSASLClientIDPath:\"\", KafkaSASLClientSecretPath:\"\", ProfilePort:0, EnableGC:true, EnableTCPDrops:false, EnableDNSTracking:false}"
time="2023-06-28T08:53:46Z" level=info msg="initializing Flows agent" component=agent.Flows
time="2023-06-28T08:53:46Z" level=debug msg="listening for new interfaces: use watching" component=agent.Flows
time="2023-06-28T08:53:46Z" level=debug msg="acquiring Agent IP" component=agent.Flows
time="2023-06-28T08:53:46Z" level=debug msg="agent IP: 172.18.0.4" component=agent.Flows
time="2023-06-28T08:53:48Z" level=info msg="Verifier error: load program: invalid argument:\n\ttrace type programs with run-time allocated hash maps are unsafe. Switch to preallocated hash maps.\n\ttrace type programs with run-time allocated hash maps are unsafe. Switch to preallocated hash maps.\n\ttrace type programs with run-time allocated hash maps are unsafe. Switch to preallocated hash maps.\n\ttrace type programs with run-time allocated hash maps are unsafe. Switch to preallocated hash maps.\n\tUnrecognized arg#0 type PTR\n\t; int kfree_skb(struct trace_event_raw_kfree_skb *args) {\n\t0: (bf) r7 = r1\n\t1: (b7) r6 = 0\n\t; __builtin_memset(&skb, 0, sizeof(skb));\n\t2: (7b) *(u64 *)(r10 -152) = r6\n\t3: (7b) *(u64 *)(r10 -160) = r6\n\t4: (7b) *(u64 *)(r10 -168) = r6\n\t5: (7b) *(u64 *)(r10 -176) = r6\n\t6: (7b) *(u64 *)(r10 -184) = r6\n\t7: (7b) *(u64 *)(r10 -192) = r6\n\t8: (7b) *(u64 *)(r10 -200) = r6\n\t9: (7b) *(u64 *)(r10 -208) = r6\n\t10: (7b) *(u64 *)(r10 -216) = r6\n\t11: (7b) *(u64 *)(r10 -224) = r6\n\t12: (7b) *(u64 *)(r10 -232) = r6\n\t13: (7b) *(u64 *)(r10 -240) = r6\n\t14: (7b) *(u64 *)(r10 -248) = r6\n\t15: (7b) *(u64 *)(r10 -256) = r6\n\t16: (7b) *(u64 *)(r10 -264) = r6\n\t17: (7b) *(u64 *)(r10 -272) = r6\n\t18: (7b) *(u64 *)(r10 -280) = r6\n\t19: (7b) *(u64 *)(r10 -288) = r6\n\t20: (7b) *(u64 *)(r10 -296) = r6\n\t21: (7b) *(u64 *)(r10 -304) = r6\n\t22: (7b) *(u64 *)(r10 -312) = r6\n\t23: (7b) *(u64 *)(r10 -320) = r6\n\t24: (7b) *(u64 *)(r10 -328) = r6\n\t25: (7b) *(u64 *)(r10 -336) = r6\n\t26: (7b) *(u64 *)(r10 -344) = r6\n\t27: (7b) *(u64 *)(r10 -352) = r6\n\t28: (7b) *(u64 *)(r10 -360) = r6\n\t29: (7b) *(u64 *)(r10 -368) = r6\n\t30: (7b) *(u64 *)(r10 -376) = r6\n\t; bpf_probe_read(&skb, sizeof(struct sk_buff), args->skbaddr);\n\t31: (79) r3 = *(u64 *)(r7 +8)\n\t32: (bf) r1 = r10\n\t;\n\t33: (07) r1 += -376\n\t; bpf_probe_read(&skb, sizeof(struct sk_buff), args->skbaddr);\n\t34: (b7) r2 = 232\n\t35: (85) call bpf_probe_read#4\n\t; enum skb_drop_reason reason = args->reason;\n\t36: (85) call unknown#195896080\n\tinvalid func unknown#195896080\n\tprocessed 37 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0" component=ebpf.FlowFetcher
time="2023-06-28T08:53:48Z" level=fatal msg="can't instantiate NetObserv eBPF Agent" error="loading and assigning BPF objects: field KfreeSkb: program kfree_skb: load program: invalid argument: invalid func unknown#195896080 (49 line(s) omitted)"
```

My yaml looks like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebpf-agent
  labels:
    app: ebpf-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebpf-agent
  template:
    metadata:
      labels:
        app: ebpf-agent
    spec:
      # the agent must be privileged
      hostNetwork: true
      # needed to allow resolving collector hostname
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: netobserv-ebpf-agent
          image: quay.io/netobserv/netobserv-ebpf-agent:main
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: EXPORT
              value: "grpc"
            - name: FLOWS_TARGET_HOST
```
